# Generated by Django 5.2.1 on 2025-06-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('serves', models.PositiveIntegerField()),
                ('overnight_prep', models.BooleanField(default=False)),
                ('time', models.PositiveIntegerField(help_text='Time in minutes')),
                ('nuisance_factor', models.FloatField()),
            ],
        ),
    ]
