# Generated by Django 5.2.1 on 2025-06-16 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_desc', models.CharField(blank=True, max_length=100)),
                ('unit_desc', models.CharField(blank=True, max_length=100)),
                ('u_quantity', models.CharField(blank=True, max_length=100)),
                ('u_desc', models.CharField(blank=True, max_length=100)),
                ('sub', models.CharField(blank=True, max_length=255, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('required', models.BooleanField(default=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.ingredient')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='meals', through='meals.MealIngredient', to='meals.ingredient'),
        ),
    ]
