# Generated by Django 5.2.1 on 2025-06-17 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_mealingredient_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='Meal',
        ),
    ]
