# Generated by Django 5.2.1 on 2025-06-27 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_rename_recipe_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='base_unit',
            field=models.CharField(choices=[('g', 'Grams'), ('ml', 'Milliliters'), ('u', 'Unit')], default='g', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='IngredientUnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_description', models.CharField(max_length=10)),
                ('multiplier', models.FloatField(help_text='Multiply this by the quantity to get value in base unit')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_conversions', to='meals.ingredient')),
            ],
            options={
                'unique_together': {('ingredient', 'unit_description')},
            },
        ),
    ]
