# Generated by Django 5.2.1 on 2025-06-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_ingredient_base_unit_ingredientunitconversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='portion_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
