# Generated by Django 5.2.1 on 2025-06-27 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_ingredient_portion_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientUnitConversion',
            new_name='IngredientMeasure',
        ),
    ]
