# Generated by Django 5.2.1 on 2025-07-05 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_rename_ingredientunitconversion_ingredientmeasure'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientNutritionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.ingredient')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.nutritiontoken')),
            ],
            options={
                'unique_together': {('ingredient', 'token')},
            },
        ),
    ]
