# Generated by Django 5.2.1 on 2025-08-19 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_nutritiontoken_ingredientnutritiontoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Household', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'All Out'), (1, 'Low'), (2, 'Plenty')], default=0)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='meals.household')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_stock', to='meals.ingredient')),
            ],
            options={
                'unique_together': {('household', 'ingredient')},
            },
        ),
    ]
