# Generated by Django 5.2.1 on 2025-09-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0009_household_householdingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='ingredient_icons/'),
        ),
    ]
