# Generated by Django 5.2.1 on 2025-09-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0011_menu_menumeal'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menumeal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='menumeal',
            name='day_number',
            field=models.PositiveIntegerField(default=1, help_text='Day index relative to menu start (1,2,3...)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menumeal',
            name='meal_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Breakfast'), (2, 'Lunch'), (3, 'Dinner')], default=3),
        ),
        migrations.AddConstraint(
            model_name='menumeal',
            constraint=models.UniqueConstraint(fields=('menu', 'day_number', 'meal_type'), name='unique_meal_per_day_and_slot'),
        ),
        migrations.AddConstraint(
            model_name='menumeal',
            constraint=models.UniqueConstraint(fields=('menu', 'meal'), name='unique_meal_per_menu'),
        ),
    ]
