# Generated by Django 5.2.1 on 2026-02-12 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0013_meal_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='instructions',
        ),
    ]
