# Generated by Django 5.2.1 on 2026-02-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0014_remove_meal_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='instructions',
            field=models.JSONField(default=list),
        ),
    ]
