# Generated by Django 5.2.1 on 2026-07-28 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0015_meal_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuFreezeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portions', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='menumeal',
            name='unique_meal_per_menu',
        ),
        migrations.AddField(
            model_name='household',
            name='number_of_members',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='menumeal',
            name='portions_multiplier',
            field=models.PositiveIntegerField(default=1, help_text="How many times this meal's yield was doubled/tripled to cover the household for this slot"),
        ),
        migrations.AddField(
            model_name='menufreezeentry',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.meal'),
        ),
        migrations.AddField(
            model_name='menufreezeentry',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeze_entries', to='meals.menu'),
        ),
    ]
