# Generated by Django 5.2.1 on 2026-07-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0017_tag_meal_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('country', 'Country'), ('region', 'Region'), ('diet', 'Diet'), ('spice_level', 'Spice level')], default='country', max_length=20),
            preserve_default=False,
        ),
    ]
